spring.application.name=pilot
server.port=6225

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pilotdb
spring.datasource.username=postgres
spring.datasource.password=waeloujdiastral481123456
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true