spring.application.name=pilot
server.port=6225

# PostgreSQL Configuration (IP dyal l'serveur)
spring.datasource.url=jdbc:postgresql://10.10.10.50:5432/pilotdb
spring.datasource.username=kyntus_user
spring.datasource.password=kyntus_password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ?? THE FIX: "create" bach y-mse7 les tables l9dam w y-creerhom mn jdid b PRAYER w FIN_SERVICE
# Mnin t-demarrih l'merra lowla f l'serveur w y-creer les tables, rje3 redha "update" bach maymse7ch lik data f l'mousta9bal!
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ? AI Microservice Configuration (IP dyal l'serveur IA)
ai.service.url=http://10.10.10.25:8000/api/v1/voice